kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
zfs_load="YES"
if_re_load="YES"
if_re_name="/boot/modules/if_re.ko"
hw.nvidiadrm.modeset=1
hw.nvidia.registry.EnableGpuFirmware=1

linux_load="YES"
linux64_load="YES"
fdescfs_load="YES"
linprocfs_load="YES"
linsysfs_load="YES"
tmpfs_load="YES"
